#!/bin/sh

chown -R arduino:arduino /var/lib/arduino-app-cli
chmod -R 775 /var/lib/arduino-app-cli

systemctl enable arduino-app-cli
systemctl enable arduino-burn-bootloader
systemctl enable arduino-avahi-serial.service

if [ "$1" = "configure" ]; then
    rm -rf /home/arduino/.local/share/arduino-app-cli
fi
