#!/bin/sh

set -e

USER_ID=1000
GROUP_NAME="arduino"
OTHER_GROUPS="sysupgrade docker"

if ! getent group "$GROUP_NAME" >/dev/null 2>&1; then
    addgroup "$GROUP_NAME"
fi

if ! getent passwd "$USER_ID" >/dev/null 2>&1; then
    adduser \
        --uid "$USER_ID" \
        --ingroup "$GROUP_NAME" \
        --home "/home/arduino" \
        --shell /bin/false \
        --disabled-password \
        "arduino" >/dev/null
fi

username="$(getent passwd $USER_ID | cut -d: -f1)"
for GROUP in $OTHER_GROUPS; do
    if ! getent group "$GROUP" >/dev/null 2>&1; then
        groupadd --system "$GROUP"
    fi
    usermod -aG "$GROUP" "$username"
done

# Starting with this version, the arduino-app-cli user directory is
# no longer located at /home/arduino/.local/share/arduino-app-cli
# Move the related file to the new location
if [ "$1" = "upgrade" ]; then
    mkdir -p /var/lib/arduino-app-cli
    cp /home/arduino/.local/share/arduino-app-cli/properties.msgpack /var/lib/arduino-app-cli || true
    cp /home/arduino/.local/share/arduino-app-cli/bootloader_burned.flag /var/lib/arduino-app-cli/default.app || true

    DEFAULT_APP_FILE="/home/arduino/.local/share/arduino-app-cli/default.app"
    if [ -f "${DEFAULT_APP_FILE}" ]; then
        sed -s "s|/home/arduino/.local/share|/var/lib|" ${DEFAULT_APP_FILE} > /var/lib/arduino-app-cli/default.app
    fi
fi
